main: io.papermc.BattleTrident.BattleTrident

name: BattleTrident
description: A simple battle royale game, but with tridents
version: 1.0.0
api-version: 1.20

commands:
  gstart:
    description: Starts a new game
    usage: /<command>
    #aliases: [gs]
  gstop:
    description: Stops the current playing game
    usage: /<command>
    #aliases: [gg]